[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "annotate_v"
version = "0.0.1"
description = "Annotates antibodies using Abnum"
license = {text = "BSD 3-clause license"}
